site_name: Accelerate AI Agents Development with GitHub Models and AI Toolkit
site_author: Carlotta Castelluccio
site_description: Learn how to accelerate the development of AI agents using GitHub models and the AI toolkit in VS Code.

# Repository ..................................................
repo_name: Accelerate AI Agents Development with GitHub Models and AI Toolkit
repo_url: https://github.com/carlotta94c/accelerate-ai-agents-development-with-gh-models-and-ai-toolkit


# Copyright ...................................................
copyright: >
  Copyright &copy; 2023 - present Microsoft

nav:
  - Home: index.md
  - Getting Started: 01_Get_Started.md
  - Model Selection: 02_Model_Selection.md
  - Model Augmentation: 03_Model_Augmentation.md
  - Agent Building: 04_Agent_Building.md
  - Migrate To Code: 05_Migrate_to_code.md
  - Bonus Evaluations: 06_Bonus_Evaluations.md
  - Summary: 07_Summary.md

plugins:
  - glightbox
  - include-markdown
  - search
  - i18n:
      docs_structure: folder
      languages:
        - locale: en
          name: English
          default: true

theme:
  name: material
  features:
    - navigation.instant
    - navigation.footer
    - content.code.copy
    - navigation.tabs.sticky 
    - content.tabs.link

  font:
    code: Roboto Mono
    text: Roboto

  palette:
    - scheme: default
      primary: black
      accent: pink
      toggle:
        icon: material/brightness-2
        name: Switch to dark mode
    - scheme: slate
      primary: amber
      accent: cyan
      toggle:
        icon: material/brightness-7
        name: Switch to light mode

markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 2
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list
  - md_in_html

# extra_javascript:
  # - js/custom.js

extra_css:
  - css/custom.css